# Generated by Django 5.2.7 on 2025-10-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LojaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cor_primaria', models.CharField(default='#FFFFFF', max_length=7)),
                ('cor_secundaria', models.CharField(default='#000000', max_length=7)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('ie', models.CharField(blank=True, max_length=14, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuração da Loja',
                'verbose_name_plural': 'Configurações da Loja',
            },
        ),
    ]
