# Generated by Django 5.2.7 on 2025-10-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='produtos_imagens/placeholder.png', null=True, upload_to='produtos_imagens/'),
        ),
    ]
