# Generated by Django 4.2.25 on 2025-11-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_de_medida',
            field=models.CharField(choices=[('mg', 'Miligrama (mg)'), ('g', 'Grama (g)'), ('kg', 'Quilograma (kg)'), ('mm', 'Milímetro (mm)'), ('cm', 'Centímetro (cm)'), ('m', 'Metro (m)'), ('km', 'Quilômetro (km)'), ('ml', 'Mililitro (ml)'), ('l', 'Litro (l)')], default='kg', max_length=2),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoria'),
        ),
    ]
