# Generated by Django 4.2.25 on 2025-11-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_categoria_produto_unidade_de_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ref',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
