# Generated by Django 4.2.25 on 2025-11-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_da_medida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
