# Generated by Django 4.2.25 on 2025-11-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_update_categoria_produto'),
        ('produtos', '0005_produto_valor_da_medida'),
    ]

    operations = [
    ]
